In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.2.6


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
## Multiply elements in an array
arr = arr*2
print(arr)

[ 2  4  6  8 10]


Multi dimensional arrays

In [8]:
array0 = np.array(3)
array1 = np.array([1,2,3,4,5]) #1d array
array2 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]) #2d array or u can sat matrix

print(array0.ndim) #.ndim is used to get the dimension of the array
print(array1.ndim)
print(array2.ndim)

0
1
2


In [ ]:
print(array0.shape)  # This gives us the shae of the array in the form of tuple
print(array1.shape)
print(array2.shape)

()
(5,)
(3, 3)


In [ ]:
print(array2[0][1]) #This is chain indexing common in python list
print(array2[0,1])  #This is mutidemensional indexing in numpy 

2
2


### Slicing 

In [ ]:
array = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])
# array[start:end:step] remember end is exclusive

#These are all row selections
print(array[0:3])
print(array[0::2]) #step 2
print(array[::-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Column selection

In [ ]:
print(array[:,0]) #this prints 1st column what we are doing is we are selecting all rows in each row we are only selecting 0th element
print(array[:,2]) 
print(array[:,-1]) 
print(array[:,0:3]) # Prints first 3 columns
print(array[:,::2])
print(array[2:,2:]) 

[ 1  5  9 13]
[ 3  7 11 15]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[11 12]
 [15 16]]


In [14]:
print(array[-1]) #-ve indexing

[13 14 15 16]


## Arthmetic

In [25]:
# Scalar arithmetic
array = np.array([1,2,3])
print(array+1) # each element will be added with 1
print(array-1)
print(array*2)
print(array/2)
print(array**5)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[  1  32 243]


In [26]:
# Vectorized math functions
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [29]:
new_array = np.array([1.01,2.5,3.78])
print(np.round(new_array)) 
print(np.floor(new_array)) 
print(np.ceil(new_array)) 

[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


In [30]:
print(np.pi)

3.141592653589793


In [ ]:
radii = np.array([1,2,3])
print(np.pi * radii**2) #

[ 3.14159265 12.56637061 28.27433388]


In [34]:
# Element-wise arithmetic
array11 = np.array([1,2,3])
array12 = np.array([4,5,6])

print(array11 + array12)
print(array11 - array12)
print(array11 * array12)
print(array11 / array12)
print(array11 ** array12)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [38]:
# Comparison operators
scores = np.array([90,65,100,73,82,69])
print(scores == 100)
print(scores >=70)

scores[scores < 70] = 0
print(scores)

[False False  True False False False]
[ True False  True  True  True False]
[ 90   0 100  73  82   0]


## Broadcasting
it allows numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match larger arrays shape

Broadcasr Rule: the dimensions have the same size or one of the dimensions has a size of 1

In [42]:
a1 = np.array([[1,2,3,4]])
a2 = np.array([[1],[2],[3],[4]])

print(a1.shape)
print(a2.shape)  # these are comaptable for broadcasting

(1, 4)
(4, 1)


In [43]:
print(a1 *a2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
table1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
table2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(table1*table2) #prints tables from 1 to 10

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Aggregate Functions
Summarize data and typically return a single value

In [49]:
agg_arr = np.array([[1,2,3,4,5],
                    [6,7,8,9,10]])

print(np.sum(agg_arr))
print(np.mean(agg_arr))
print(np.std(agg_arr)) # standard deviation
print(np.var(agg_arr)) # variance
print(np.max(agg_arr))
print(np.argmax(agg_arr)) # to get the index of maximum

55
5.5
2.8722813232690143
8.25
10
9


In [50]:
print(np.sum(agg_arr, axis=0)) #sums the elements in column
print(np.sum(agg_arr, axis=1)) #sums the elements in row

[ 7  9 11 13 15]
[15 40]


## Filtering
It refers to the process of selecting elements from an array that match a given condition

In [ ]:
# Filtering using boolean indexing
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages<18] # this will flaten our array i.e., becomes 1D
print(teenagers)
adults = ages[(ages>=18) & (ages<65)] # here we use & insted of and because numpy is written in 'C'
print(adults)
outliers = ages[(ages<18) | (ages>65)]
print(outliers)
evens = ages[ages%2 == 0]
print(evens)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[17 16 15 99]
[20 16 30 18 22 18 20]


In [ ]:
# Filtering using WHERE()
## Using where function which preserves the shape on given array

adults1 = np.where(ages>=18,ages,0) #Takes 3 arguments(condition,input_array,fill_value)
print(adults1)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


## Random Numbers

In [83]:
## Generating random numbers using numpy which is fater compared to buitin random module
rng = np.random.default_rng()
print(rng.integers(1,7)) #last number is exclusive
print(rng.integers(1,101,size=3)) #gives 3 random numbsers between 1 and 100
print(rng.integers(1,101,size=(3,2)))

6
[21 26 89]
[[99 18]
 [46 14]
 [ 9 59]]


In [85]:
rng = np.random.default_rng(seed=42) #When you fix the seed with a number every time the generated numbers remain same 42 doesnt mean anything its just fixing a seed
                                     #In Data Science, you'll often see this used when splitting data into "Training" and "Testing" sets.
print(rng.integers(1,7)) #last number is exclusive
print(rng.integers(1,101,size=3)) #gives 3 random numbsers between 1 and 100
print(rng.integers(1,101,size=(3,2)))

1
[78 66 44]
[[44 86]
 [ 9 70]
 [21 10]]


In [89]:
print(np.random.uniform()) # Uniform means uniform distribution this will pick decimal number between 0 and 1

0.6218651082102635


In [96]:
print(np.random.uniform(low=-1,high=1)) #picks a number in uniform distribution from -1 to 1

-0.21381125645785648


In [99]:
np.random.seed(seed=22)
print(np.random.uniform(low=-1,high=1,size=(3,2))) 

[[-0.58307893 -0.03663788]
 [-0.15892393  0.718364  ]
 [-0.65767689 -0.32227208]]


In [105]:
#shuffle, random choice
rng = np.random.default_rng()
fruits = np.array(['Grape','Banana','Kiwi','Apple'])
rng.shuffle(fruits) #shuffle the list
print(fruits)

fruit = rng.choice(fruits,size=(2)) #random choice
fruit = rng.choice(fruits,size=(2,2)) 
print(fruit)

['Grape' 'Banana' 'Kiwi' 'Apple']
[['Grape' 'Kiwi']
 ['Apple' 'Kiwi']]
